brew 'ansible'
brew 'antigen'
brew 'awscli'
brew 'git'
brew 'mise'
brew 'terraform'
brew 'tree'
brew 'wget'

cask '1password'
cask '1password-cli'
cask 'docker'
cask 'fantastical'
cask 'firefox'
cask 'google-chrome'
cask 'intellij-idea'
cask 'iterm2'
cask 'obsidian'
cask 'rectangle'
cask 'visual-studio-code'

brew 'mas'
mas '1Password for Safari', id: 1569813296
